
title : Jose Sebastian Villalba
logo: /assets/img/PXL_20230708_005017470.jpg
location: "Winnipeg,MC - Canada"
description: Machine Learning Engineer and Product Manager. Winnipeg,MB - CA
linkedin: "josesvillalba"
twitter : "Hombre_Lunarejo"
theme: jekyll-theme-minimal

